# This is a basic workflow to help you get started with Actions

name: test-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-crawler]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout backend repo 
        uses: actions/checkout@v2
        with:
          path: backend-repo

      - name: Checkout docusaurus repo
        uses: actions/checkout@v2
        with:
          repository: redis-developer/redis-developer.github.io
          path: docusaurus-repo

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name : Run script
        env:
          PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
          PORT: ${{ secrets.PORT }}
          REDIS_CONNECTION_STRING: ${{ secrets.REDIS_CONNECTION_STRING }}
        run: |
          cd ./backend-repo
          npm ci
          npm run crawler

